import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { DataProvider } from "./context/DataContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DataProvider>
        <body
          className={`${inter.className} flex flex-col justify-center p-4 lg:p-12 w-full h-full bg-gray-100`}
        >
          {children}
        </body>
      </DataProvider>
    </html>
  );
}
